CREATE TABLE INSTRUCAO(
  INSTRUCAO_ID SERIAL PRIMARY KEY,
  DESCRICAO VARCHAR(50),
  TEXTO_SQL VARCHAR(1000),
  VERSAO INTEGER,
  INSTRUCAO INTEGER,
  ERRO CHAR(1) DEFAULT 'N',
  EXECUTADA CHAR(1) DEFAULT 'N',
);

CREATE TABLE USUARIO (
  USUARIO_ID SERIAL PRIMARY KEY,
  NOME VARCHAR(100),
  EMAIL VARCHAR(100) UNIQUE,
  SENHA VARCHAR(12),
  URL_GOOGLE VARCHAR(1000)
);

CREATE TABLE BANCO (
  BANCO_ID SERIAL PRIMARY KEY,
  NOME VARCHAR(20) 
);

CREATE TABLE CONTA (
  CONTA_ID SERIAL PRIMARY KEY,
  BANCO_ID INTEGER,
  USUARIO_ID INTEGER,
  NOME VARCHAR(20),
  CONSTRAINT FK_CONTA_BANCO FOREIGN KEY (BANCO_ID) REFERENCES BANCO(BANCO_ID),
  CONSTRAINT FK_CONTA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID),
  CONSTRAINT UNIQUE_NOME_USUARIO UNIQUE (NOME, USUARIO_ID)
);

CREATE TABLE CATEGORIA (
  CATEGORIA_ID SERIAL PRIMARY KEY,
  USUARIO_ID INTEGER,
  NOME VARCHAR(20),
  CONSTRAINT FK_CATEGORIA_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

CREATE TABLE LANCAMENTO (
  LANCAMENTO_ID SERIAL PRIMARY KEY,
  CONTA_ID INTEGER,
  CATEGORIA_ID INTEGER,
  TITULO VARCHAR(100),
  DESCRICAO VARCHAR(1000),
  VALOR NUMERIC(15,2),
  DATA DATE,
  CONSTRAINT FK_LANCAMENTO_CONTA FOREIGN KEY (CONTA_ID) REFERENCES CONTA(CONTA_ID),
  CONSTRAINT FK_LANCAMENTO_CATEGORIA FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA(CATEGORIA_ID)
);